### ISSUE TITLE
lots of exc bad accesses...

### ISSUE THREAD

**Issue by udaypatial** [VeinGuo/VGPlayer#14]

**Comment by VeinGuo** [comment]
@udaypatial Hello, can you tell me where exc bad accesses? I can try to optimize it, thanks.

**Comment by mittenimraum** [comment]
For example here:

![bildschirmfoto 2017-09-07 um 08 44 41](https://user-images.githubusercontent.com/1453177/30149701-ea4f24fe-93a8-11e7-96fc-805df13dfc8d.png)

Is there maybe any downloading going on after `deinit`? The error pop up during dismissing a view controller.

**Comment by mittenimraum** [comment]
The error also appears when loading a video without calling `VGPlayerCacheManager.shared.cleanAllCache()` before in some cases.

**Comment by VeinGuo** [comment]
@mittenimraum  Hi ,The normal situation does not appear, because each time you add the task will cancel these requests, and the release of the object will cancel the download task, can provide a more detailed operation?

![image](https://user-images.githubusercontent.com/14232017/30265263-3fa97b94-970e-11e7-8793-2092414ed3ee.png)
![image](https://user-images.githubusercontent.com/14232017/30265353-7c46f158-970e-11e7-95c4-9795fd4ab07a.png)
